In [2]:
import numpy as np
import matplotlib.pyplot as plt
from diskprojection import disk_observation

HD163296_13CO = disk_observation('/data/shared/HD163296_MAPS/HD_163296_13CO_220GHz.robust_0.5.clean.JvMcorr.image.pbcor.fits')
#note that chans does NOT correspond to the channel maps
HD163296_13CO.get_emission_surface_diagnostic(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_13CO')

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([4.82379318, 4.78931544, 4.77137445, ..., 4.75154894, 4.79886899,
        4.8961598 ]),
 array([ 25.61239041, -25.73605539, -25.74979594, ..., -25.72231483,
         26.03834755,  25.68109318]),
 array([0.005608  , 0.00508001, 0.00495794, ..., 0.00557549, 0.00500523,
        0.00653387]),
 array([-1340.00001332, -1340.00001332, -1340.00001332, ...,
        12659.99998648, 12659.99998648, 12659.99998648]),
 array([ 783.,  786.,  787., ..., 1260., 1263., 1266.]),
 array([1968.,   66.,   65., ...,   72., 1961., 1981.]),
 array([1943.,  108.,  108., ...,  103., 1981., 1935.]))

In [8]:
HD163296_CO = disk_observation('/data/shared/HD163296_MAPS/HD_163296_CO_220GHz.robust_0.5.clean.JvMcorr.image.pbcor.fits')
#note that chans does NOT correspond to the channel maps
HD163296_CO.get_emission_surface_diagnostic(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_CO')

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


IndexError: index -2 is out of bounds for axis 0 with size 1

In [9]:
HD163296_C18O = disk_observation('/data/shared/HD163296_MAPS/HD_163296_C18O_220GHz.robust_0.5.clean.JvMcorr.image.pbcor.fits')
#note that chans does NOT correspond to the channel maps
HD163296_C18O.get_emission_surface_diagnostic(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_C18O')

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([4.97506205, 4.95770532, 4.86866947, ..., 4.87264053, 4.89262973,
        4.91261903]),
 array([-25.61239041, -25.62613096,  23.29023699, ...,  24.81543835,
         24.81543835,  24.81543835]),
 array([0.00475593, 0.00515599, 0.00400798, ..., 0.00539827, 0.00554435,
        0.00459196]),
 array([-1340.0000306 , -1340.0000306 , -1340.0000306 , ...,
        12659.99996547, 12659.99996547, 12659.99996547]),
 array([ 778.,  779.,  782., ..., 1267., 1268., 1269.]),
 array([  64.,   63., 1892., ..., 1932., 1932., 1932.]),
 array([ 119.,  119., 1850., ..., 1921., 1921., 1921.]))

In [12]:
HD163296_HCN = disk_observation('/data/shared/HD163296_MAPS/HD_163296_HCN_260GHz_hf1.robust_0.5.clean.JvMcorr.image.pbcor.fits')
#note that chans does NOT correspond to the channel maps
HD163296_HCN.get_emission_surface_diagnostic(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_HCN')

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([4.95137425, 4.93174628, 4.9480443 , ..., 4.97931339, 4.98335035,
        4.99615292]),
 array([-20.26731537, -20.28105593, -19.47036331, ...,  19.29173613,
         19.1543306 , -20.55586698]),
 array([0.00414617, 0.00370757, 0.0031873 , ..., 0.00261579, 0.00245182,
        0.00304004]),
 array([-1340.00003626, -1340.00003626, -1340.00003626, ...,
        12659.99996466, 12659.99996466, 12659.99996466]),
 array([ 520.,  521.,  522., ..., 1015., 1016., 1017.]),
 array([  26.,   25.,   80., ..., 1451., 1452.,   28.]),
 array([  34.,   34.,   38., ..., 1488., 1477.,   11.]))

In [11]:
HD163296_C2H = disk_observation('/data/shared/HD163296_MAPS/HD_163296_C2H_260GHz_hf4.robust_0.5.clean.JvMcorr.image.pbcor.fits')
#note that chans does NOT correspond to the channel maps
HD163296_C2H.get_emission_surface_diagnostic(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_C2H')

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


IndexError: index -2 is out of bounds for axis 0 with size 1