In [1]:
import numpy as np
import matplotlib.pyplot as plt
from diskprojection import disk_observation

rms_13CO = 0.00146449
min_Fnu_13CO = 5 * rms_13CO
HD163296_13CO = disk_observation('/data/shared/HD163296_MAPS/HD_163296_13CO_220GHz.robust_0.5.clean.JvMcorr.image.pbcor.fits')
HD163296_13CO.get_emission_surface_v2(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_13CO_v2', min_Fnu = min_Fnu_13CO)

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([0.33663234, 0.34542415, 0.34903538, ..., 0.36076852, 0.3607782 ,
        0.34139995]),
 array([0.05496221, 0.05496221, 0.02748111, ..., 0.01374055, 0.04122166,
        0.04122166]),
 array([0.01826611, 0.01939018, 0.01654984, ..., 0.01836775, 0.01623052,
        0.0161432 ]),
 array([ 1459.99998664,  1459.99998664,  1659.99998664, ...,
        10059.99998652, 10059.99998652, 10259.99998651]),
 array([1039., 1040., 1039., ..., 1006., 1007., 1007.]),
 array([1030., 1029., 1030., ..., 1027., 1030., 1028.]),
 array([1021., 1022., 1019., ..., 1021., 1020., 1022.]))

In [2]:
rms_CO = 0.00168616
min_Fnu_CO = 5 * rms_CO
HD163296_CO = disk_observation('/data/shared/HD163296_MAPS/HD_163296_CO_220GHz.robust_0.5.clean.JvMcorr.image.pbcor.fits')
HD163296_CO.get_emission_surface_v2(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_CO_v2', min_Fnu = min_Fnu_CO)

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([0.23091413, 0.24763145, 0.26480433, ..., 0.33122044, 0.30290911,
        0.28382024]),
 array([0.05496221, 0.05496221, 0.05496221, ..., 0.06870276, 0.06870276,
        0.06870276]),
 array([0.02665971, 0.02928184, 0.03171589, ..., 0.03031836, 0.03107183,
        0.03131465]),
 array([ 1059.99999311,  1059.99999311,  1059.99999311, ...,
        10259.99999222, 10459.9999922 , 10659.99999218]),
 array([1033., 1034., 1035., ..., 1008., 1009., 1010.]),
 array([1030., 1030., 1030., ..., 1030., 1029., 1029.]),
 array([1021., 1021., 1021., ..., 1022., 1023., 1023.]))

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from diskprojection import disk_observation

rms_C18O = 0.00102492
min_Fnu_C18O = 5 * rms_C18O
HD163296_C18O = disk_observation('/data/shared/HD163296_MAPS/HD_163296_C18O_220GHz.robust_0.5.clean.JvMcorr.image.pbcor.fits')
HD163296_C18O.get_emission_surface_v2(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_C18O_v2', min_Fnu = min_Fnu_C18O)

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([0.31845757, 0.31831012, 0.31543897, ..., 0.41636631, 0.40326877,
        0.39803383]),
 array([0.        , 0.02748111, 0.04122166, ..., 0.01374055, 0.02748111,
        0.02748111]),
 array([0.00935596, 0.00925953, 0.01040299, ..., 0.01344843, 0.01213149,
        0.01081823]),
 array([1059.99996873, 1259.99996867, 1259.99996867, ..., 9859.99996625,
        9859.99996625, 9859.99996625]),
 array([1039., 1038., 1039., ..., 1004., 1005., 1006.]),
 array([1026., 1029., 1027., ..., 1029., 1030., 1031.]),
 array([1021., 1020., 1023., ..., 1019., 1019., 1018.]))

In [2]:
rms_HCN = 0.00096755
min_Fnu_HCN = 5 * rms_HCN
HD163296_HCN = disk_observation('/data/shared/HD163296_MAPS/HD_163296_HCN_260GHz_hf1.robust_0.5.clean.JvMcorr.image.pbcor.fits')
HD163296_HCN.get_emission_surface_v2(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_HCN_v2', min_Fnu = min_Fnu_HCN)

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([0.29580694, 0.31845757, 0.33511453, 0.30743755, 0.33122044,
        0.35000997, 0.3689268 , 0.26480433, 0.27587494, 0.30020216,
        0.3313996 , 0.34257978, 0.36691375, 0.38500091, 0.40326877,
        0.3321702 , 0.33848394, 0.36323139, 0.37117567, 0.38803528,
        0.40518067, 0.4157294 , 0.43362534, 0.45169783, 0.46423669,
        0.47303373, 0.49209847, 0.50369334, 0.51744944, 0.3665297 ,
        0.38150232, 0.38797928, 0.40413849, 0.42888696, 0.44535831,
        0.46210824, 0.47910753, 0.49633056, 0.50688058, 0.51839854,
        0.52538646, 0.67142645, 0.40106343, 0.41575459, 0.44039031,
        0.45556957, 0.47110894, 0.48697395, 0.50313381, 0.51151918,
        0.76695873, 0.78652762, 0.80611767, 0.82301938, 0.40824086,
        0.42173523, 0.44609729, 0.46022037, 0.47476604, 0.48027138,
        0.49584332, 0.51172317, 0.71951858, 0.73522373, 0.39471862,
        0.40669742, 0.4305464 , 0.44336238, 0.46750703, 0.4810019 ,
        0.50535203, 0.51940415, 0.39568952, 0.40

In [3]:
rms_C2H = 0.00115811
min_Fnu_C2H = 5 * rms_C2H
HD163296_C2H = disk_observation('/data/shared/HD163296_MAPS/HD_163296_C2H_260GHz_hf4.robust_0.5.clean.JvMcorr.image.pbcor.fits')
HD163296_C2H.get_emission_surface_v2(inc=46.7, PA=313.3, chans = [28, 98], r_max = 5, 
                                              directory='/data/shared/diskprojectiontest/HD163296_C2H_v2', min_Fnu = min_Fnu_C2H)

Using -1.34 km/s to 12.66 km/s, and 0.00" to 5.00".
Rotating data cube...
Detecting peaks...


(array([1.70501267, 1.75922059, 1.77698358, ..., 0.40313502, 0.38382007,
        4.24060691]),
 array([ 1.49772025, -1.59390412, -1.58016357, ..., -0.05496221,
        -0.05496221,  0.17862719]),
 array([0.00989951, 0.00600405, 0.00773279, ..., 0.01102194, 0.00950617,
        0.00658755]),
 array([ 1259.99999681,  1459.99999682,  1459.99999682, ...,
        12459.99999735, 12459.99999735, 12659.99999736]),
 array([792., 782., 783., ..., 748., 749., 738.]),
 array([878., 769., 770., ..., 769., 769., 918.]),
 array([766., 650., 650., ..., 762., 762., 630.]))